---
- hosts: all

  become: true
  tasks:    
    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - git
        - sysstat
     
    - name: Touch a file, using symbolic modes to set the permissions (equivalent to 0644)
      file:
         path: /tmp/foo.conf
         state: touch
         mode: u=rw,g=r,o=r
